MyFirstProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.urls import path
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('food.urls')), #! path('food/',include('food.urls')),  告知要查app [food]的urls.py 來看網址
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#! path('', include('food.urls')),
#? if http://127.0.0.1:8000/ will look for urls.py under food app
#! the main point is path(''
"""
from . import views #     . means current directory     <import views.py>
from django.urls import path


urlpatterns = [
    path('hello/', views.helloworld,name='helloworld'),     #in views.py use function helloworld #! 需要告知default urls連到這邊來
    path('item/',views.item,name='item'),
]
"""
#? what will works now is http://127.0.0.1:8000/hello/
#?                        http://127.0.0.1:8000/item/

#! if i set path('food', include('food.urls')),
#! what will works now is http://127.0.0.1:8000/food/hello/
#!                        http://127.0.0.1:8000/food/item/ 


food/urls.py
from . import views #     . means current directory     <import views.py>
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


#*Namespacing
#* in case of your co-workers name their URLs as same asa your
#* in this project we named 3 url page as item, show, detail
#* even other ppl name the same name as we did Django will not confuss
app_name = "nameURL_4_nameSpacing_frm_urls-py"
urlpatterns = [
    #http://127.0.0.1:8000/item/
    path('item/', views.item,name='item'),     #in views.py use function helloworld #! 需要告知default urls連到這邊來
    #http://127.0.0.1:8000/
    path('', views.show,name='show'),
    #http://127.0.0.1:8000/item/1    1 is item_id cant ba any # in the table
    path('<int:item_id_frm_views_from_def_detail>/', views.detail,name="detail"),
] #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        #! use str tried also worked
        #! <str:item_id_frm_views_from_def_detail>
#! 前面有宣告過告知default urls連到這邊來所以這個就不用打
##django has no obligation to look at this file, django will only look 
# at the urls.py which in in the prokect folder "MyFirstProject"
##C:\Users\Bruce Ashbee\Documents\MyFirstProject\MyFirstProject\urls.py
#
#* from MyFirstProject\urls.py
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('', include('food.urls')), #! path('food/',include('food.urls')),  告知要查app [food]的urls.py 來看網址
# ]   #?path(''  >> 網址後面是空個的話 <http://127.0.0.1:8000/>
      #? 取找food app裡面的urls.py
      #?也可以不要設定是空的

#urlpatterns += staticfiles_urlpatterns()

food/models.py
from django.db import models
#! models right here actually define the structure of how these tables will be created that is 
#! these models define which columns the table would have what would be the name of the table what would
#! be the multiple fields inside the table and the data types as well.
# Create your models here.
#? go to setting.py look for  database and change the database that you wanna use

#set table name here
# class name is the table name
class Item_frm_model(models.Model):   #Primary Key is not given, django will generate filed ID automatically for us 
    def __str__(self): 
        return self.item_name #這個設定只會在查詢時顯示item_name
    #設定 table列表fields
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()


#* FYI <python shell>
#! can type commands for check table and objects
#! EXP. Item_frm_model.objects.all() will not juz show numbers of objects in the table only
#! so can show the name of object too

food/views.py
from django.shortcuts import render
from django.http import HttpResponse
# Create your views here.
#? for retriving data for simplest way
from .models import Item_frm_model  ##load Item table from models.py
#? from models.py under current folder 
#? import Item table

from django.template import loader
'''
food/urls.py
urlpatterns = [
    path('hello/', views.helloworld,name='helloworld'),     #in views.py use function helloworld #! 需要告知default urls連到這邊來
    path('item/',views.item,name='item'),
]
'''
#food/urls.py
#path('hello/', views.helloworld,name='helloworld'),     #in views.py use function helloworld #! 需要告知default urls連到這邊來
#? http://127.0.0.1:8000/item/
def item(request):#! accept request from the user
    item_list = Item_frm_model.objects.all()   
              #!Item from models
    ## retrieving all objects from table "Item" > item_list
    #template = loader.get_template("food/index.html") #not using coz of using render
    #! line 23 is not needed coz we use render at the line 36,
    #! if wanna use line 23, line 37 is needed and line 33 is not required anymore
    #* tell django where to location the template
    #* MyFirstProject\food\templates\food\index.html
    context ={
        "item_list_frm_views_pass2template" : item_list,
    }   #name a variable item_list_pass2template for passing data to template
        #pass item_list2 to \MyFirstProject\food\templates\food\index.html
    return render(request,"food/index.html",context) #! pass to template food/index.html
                  #pass the request
                           #the location of template
                                            #pass the context
    #return HttpResponse(template.render(context,request)) # display item_list
    #! we can use render instead of using Http HttpResponse
    ##                 
    #! context is set to empty
    #!    context ={
    #!   
    #!
    ##PizzaBurgerBurritofrench fries 
    #* not in readable format
    #* so we shall use TEMPLATE to display 
    #! context is used for passing data from database to template
                       
                       
#? http://127.0.0.1:8000/item-test/
def show(request):
    return HttpResponse('<h1>This is an item view</h1>')

def detail(request,item_id_frm_views_from_def_detail):#accept request
    item = Item_frm_model.objects.get(pk=item_id_frm_views_from_def_detail) #accept item_id <PK> to collect all detail data
    context = {
        'item_list_frm_views_frm_def_detail' : item,
    }
    return render(request,"food/detail.html",context)
    #*                    template folder food\templates\food\detail.html
    #* now got to food/urls to create PATH of the view

food/templates/food/detail.html
<h1>{{ item_list_frm_views_frm_def_detail.item_name }}</h1>
<h2>{{ item_list_frm_views_frm_def_detail.item_desc }}</h2>
<h3>{{ item_list_frm_views_frm_def_detail.item_price }}</h3>

food/templates/food/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static '/food/style.css' %}">
</head>
<body>
    <h1>item views with details link</h1>
    {% for item_frm_index_html in item_list_frm_views_pass2template %}
    <!--item_list_pass2template is from MyFirstProject\food\views.py-->
    <!--  for loop -->
    <!-- remeber to keep a space after %-->
        <ul>
            <li>
                <!--line 19  /item/   its a hard code URLs   look at line 20 to change it and get name of URLs from urls.py-->   
                <!--<a href="/item/{{item_frm_index_html.id }}"> {{item_frm_index_html.id }} -- {{ item_frm_index_html.item_name }}</a>-->
                                                 <!--get id from item table --> 
                <a href="{% url 'nameURL_4_nameSpacing_frm_urls-py:detail' item_frm_index_html.id %}"> {{item_frm_index_html.id }} -- {{ item_frm_index_html.item_name }}  <!--get item_name from item table-->
                    <!--  look for urls.py a URL name detail -->
                                      <!--item_frm_index_html.id   is the PK from item table-->
            </li>
        </ul>
    {% endfor %}
    <!-- end of for loop-->

    
</body>
</html>
